require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'destinow' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Functions'

  target 'destinowTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'destinow-tvOS' do
  # Pods for destinow-tvOS

  target 'destinow-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    if config.name != 'Release'
      config.build_settings["VALID_ARCHS[sdk=iphonesimulator*]"] = "arm64, arm64e, armv7, armv6, i386, x86_64"
    end
  end
end
